### PR TITLE
Elasticsearch mapping update

### PR DESCRIPTION
**Pull request by plithnar**
### Description

Commit messages got lost. Here they are:
Removing 'nested' from the submitter/releaser object to try and make the facets work.
Import reordering to make pylint happy
Resetting the count for the test. Initial update to account for "nested" type was mistaken.

### Issues Resolved

[List any existing issues this PR resolves]

### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by GitBytes** [comment]
@plithnar Make sure this is the final iteration before we merge this please. If we need to keep iterating and this goes through, it will result in large chain of events to happen and is very painful operationally to do yet again every time changes are made. In our case, every release (whole chain unto itself), can cause up to a whole work week of delay on the production environment to fix or update.

**Comment by plithnar** [comment]
@GitBytes, Worked with Dave Brown to validate that facets are now creating as expected. There WILL be more mappings needed when the additional project participant information is added to the ES Index, but that doesn't appear to have been part of this last push. That being said, I have documented the necessary steps for validating that the mappings are correct before submitting a pull request so that I can be sure that the search tool works as expected.

**Comment by GitBytes** [comment]
@plithnar @dmlb2000 We ready to make a release cut then on this? Thanks.

**Comment by GitBytes** [comment]
@dmlb2000 bump (release)

**Pull request merged**
