### PR TITLE
Add additional Mappings from Degans repository

### LINKED ISSUE #81: Elasticsearch Mapping needs to get updated
### Pacifica Policy version
Master
### Pacifica Core Software versions
1.0b
### Platform Details
Any
### Scenario:
With the additions to relationships we need to update the elasticsearch mapping to match that.

### PR DESCRIPTION
**Pull request by dmlb2000**
### Description

This adds some additional elasticsearch mappings from Degan's repository.

### Issues Resolved

Fix #81 
### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
@plithnar Looks like everything passed and is ready to go, are you ready to merge?

**Review by dmlb2000 — COMMENTED** [review]
Seems fine to me, I'm curious about how manipulating the mapping changes the total number of document elasticsearch registers... was stuff getting dropped before?

**Comment by plithnar** [comment]
As new fields are moved and added, if we want to build facets for them (and they are text fields), we need to do one of two things:
1. Set the field for the facet to "type": "keyword"
2. Set the field for the facet to "type": "text", "fielddata": True
This is due to the defaults for Elasticsearch not allowing fielddata search on text fields. Of note, the first option is the preferred one. 

Since the facets are built by the Searchkit npm module, we do not have access to the raw queries that they use for facet queries.

**Comment by plithnar** [comment]
@dmlb2000 I believe it has to do with adding the fields in the mapping as keyword type. Doing this exposes the field to more search capabilities. 
That being said, I do believe this is ready to merge.

**Pull request merged**
