### PR TITLE
Suggested changes for uploader precondition validation

### LINKED ISSUE #7: Uploader Validation for Metadata
### Pacifica Policy version
master
### Pacifica Core Software versions
master
### Platform Details
Any
### Scenario:
Need to validate the format of the ingest metadata before returning.
### Steps to Reproduce:
1. pass hash without destination table entry.
### Expected Result:
Some error claiming faulty metadata
### Actual Result:
passed with flying colors.

### PR DESCRIPTION
**Pull request by kauberry**
### Description

Changes the validation logic for instruments/proposals/submitters to just check the validity of the object, without putting cross-reference constraints on the upload. 

We should probably let the researchers worry about whether a particular instrument/proposal combo is OK, so long as all the numbers are valid.

### Issues Resolved

#7

### Check List

- [x] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by dmlb2000** [comment]
There's some aspects of this commit that I like:
 * The 412 is a better return code for the request if it fails...
 * Moving the HTTPError raise into the validate method does provide it context for why it failed... which is good
 * Making an `is_valid_object_id` in the admin class is a good idea, just the implementation shouldn't have the mapping stuff in it.

The other aspect I'm going to want to verify with Dave M as to where through the process the policy should be applied.

**Comment by kauberry** [comment]
Fair enough on the last point. Wasn’t thinking ahead far enough, but needed a way to deal with the differences between what one system calls things vs. the other (submitter and user, e.g.). Could probably make it to where the the mapping is passed into the function or something like that.

**Comment by kauberry** [comment]
This should clear up the issue with removing the mapping from the implementation of the object validator. I also put back in the instrument/proposal/user cross-reference checks while still reconciling it with the case of instrument operators who are not EMSL staff members, but are instrument custodians.

**Review by dmlb2000 — APPROVED** [review]
This is much better, Thanks!

**Pull request merged**
